"""add fact_review

Revision ID: 26e3e82dff3b
Revises: 2ce46a888019
Create Date: 2026-06-15 00:12:10.417915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e3e82dff3b'
down_revision: Union[str, Sequence[str], None] = '2ce46a888019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['lesson_fact.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fact_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_review_fact_id'), ['fact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_review_reviewed_at'), ['reviewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_review_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_review_user_id'))
        batch_op.drop_index(batch_op.f('ix_fact_review_reviewed_at'))
        batch_op.drop_index(batch_op.f('ix_fact_review_fact_id'))

    op.drop_table('fact_review')
    # ### end Alembic commands ###
