"""lessons, quizzes, count goal

Revision ID: 4b31b3dc086c
Revises: 26e3e82dff3b
Create Date: 2026-06-15 00:38:43.780190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b31b3dc086c'
down_revision: Union[str, Sequence[str], None] = '26e3e82dff3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('choices', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('answer_index', sa.Integer(), nullable=True))

    with op.batch_alter_table('drill_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct', sa.Boolean(), nullable=True))

    with op.batch_alter_table('lesson_fact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), server_default='', nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_items', sa.Integer(), server_default=sa.text('5'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('daily_items')

    with op.batch_alter_table('lesson_fact', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('drill_log', schema=None) as batch_op:
        batch_op.drop_column('correct')

    with op.batch_alter_table('drill', schema=None) as batch_op:
        batch_op.drop_column('answer_index')
        batch_op.drop_column('choices')
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###
