"""initial schema

Revision ID: ba5ea1a237c4
Revises: 
Create Date: 2026-06-14 23:37:50.427171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5ea1a237c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('default_priority', sa.Integer(), nullable=False),
    sa.Column('core_idea', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_slug'), ['slug'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active_days_per_week', sa.Integer(), nullable=False),
    sa.Column('daily_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('drill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('script', 'reflection', 'rehearsal', 'checklist', 'audit', 'record_review', name='drillkind', native_enum=False), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'title', name='uq_drill_domain_title')
    )
    with op.batch_alter_table('drill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drill_domain_id'), ['domain_id'], unique=False)

    op.create_table('lesson_fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'order', name='uq_fact_domain_order')
    )
    with op.batch_alter_table('lesson_fact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_fact_domain_id'), ['domain_id'], unique=False)

    op.create_table('source_ref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('cached_path', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_domain_pref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'domain_id', name='uq_pref_user_domain')
    )
    with op.batch_alter_table('user_domain_pref', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_domain_pref_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_domain_pref_user_id'), ['user_id'], unique=False)

    op.create_table('drill_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drill_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('outcome', sa.Enum('done', 'skipped', 'snoozed', name='logoutcome', native_enum=False), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('difficulty IS NULL OR (difficulty BETWEEN 1 AND 3)', name='ck_log_difficulty_range'),
    sa.ForeignKeyConstraint(['drill_id'], ['drill.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drill_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drill_log_drill_id'), ['drill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drill_log_logged_at'), ['logged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_drill_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drill_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drill_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_drill_log_logged_at'))
        batch_op.drop_index(batch_op.f('ix_drill_log_drill_id'))

    op.drop_table('drill_log')
    with op.batch_alter_table('user_domain_pref', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_domain_pref_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_domain_pref_domain_id'))

    op.drop_table('user_domain_pref')
    op.drop_table('source_ref')
    with op.batch_alter_table('lesson_fact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_fact_domain_id'))

    op.drop_table('lesson_fact')
    with op.batch_alter_table('drill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drill_domain_id'))

    op.drop_table('drill')
    op.drop_table('user')
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_slug'))

    op.drop_table('domain')
    # ### end Alembic commands ###
