"""level + ordering for sections

Revision ID: de3dce754b5d
Revises: 4b31b3dc086c
Create Date: 2026-06-15 01:15:50.675187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3dce754b5d'
down_revision: Union[str, Sequence[str], None] = '4b31b3dc086c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Enum('beginner', 'intermediate', 'advanced', name='level', native_enum=False), server_default='beginner', nullable=False))
        batch_op.add_column(sa.Column('order', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('lesson_fact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Enum('beginner', 'intermediate', 'advanced', name='level', native_enum=False), server_default='beginner', nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_fact_domain_order'), type_='unique')
        batch_op.create_unique_constraint('uq_fact_domain_level_order', ['domain_id', 'level', 'order'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_fact', schema=None) as batch_op:
        batch_op.drop_constraint('uq_fact_domain_level_order', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_fact_domain_order'), ['domain_id', 'order'])
        batch_op.drop_column('level')

    with op.batch_alter_table('drill', schema=None) as batch_op:
        batch_op.drop_column('order')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
